name: Validate JSON

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate JSON
        run: |
          find code/src/ -type f -name '*.json' | xargs jq -r .

